services:
  api:
    build:
      context: ./MedicineReminder
      target: final
    ports:
      - "5000:8080"
    container_name: medicine_reminder_api
    hostname: medicine_reminder_host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_SECRET=${JWT_SECRET}
      - MSSQL_CONNECTION_STRING=${MSSQL_CONNECTION_STRING}
    depends_on:
      db:
        condition: service_started
        restart: true
    restart: on-failure:10

  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    container_name: medicine_reminder_mssql
    hostname: mssql_host
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    volumes:
      - medicine_reminder_db:/var/opt/mssql

volumes:
  medicine_reminder_db: